# 端口号
server:
  port: 8080
spring:
  shardingsphere:
    # 配置是否显示shardingjdbc的sql，shardingjdbc来管理数据源
    props:
      sql:
        show: true
        #数据源配置
    datasource:
      names: ds0,ds1
      #配置主数据源 ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.80.21:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        maxPoolSize: 100
        minPoolSize: 5
        # 配置从数据源 ds2
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.80.31:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        maxPoolSize: 100
        minPoolSize: 5
        # 配置默认数据源也就是主数据源，若不配置则会认为都是从数据源，只有配置这个才能实现读写分离，后面也要配置主从复制机制，因为读写分离要依赖于主从复制
    sharding:
      default-data-source-name: ds0
      # 配置分表分库策略：
      tables:
        # 逻辑表名
        user_order:
          # 配置数据库的分布式主键这里使用雪花算法
          key-generator:
            column: orderid
            type: UUID
          # 数据节点，分片方式：数据源$-->{0..1}.逻辑表$->{0...2}，将用户订单表分为2021年123月的数据和2022年123月的数据，所以前提要建6个表
          actual-data-nodes: ds1.user_order_$->{2021..2022}${(1..3).collect{t->t.toString().padLeft(2,'0')}}
          table-strategy:
            #inline:
#              sharding-column: yearmonth #数据源分片字段
#              algorithm-expression: user_order_$->{yearmonth}
            standard:
              sharding-column: yearmonth #数据源分片字段
              preciseAlgorithmClassName: com.dhj.shardingjdbc.config.YearMonthAlgorithm