# 端口号
server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true #是否覆盖相同实例对象
  profiles:
    active: yearmonth
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dhj.shardingjdbc.entity